### ISSUE TITLE
Default field :type behavior change in version 3.0.0

### ISSUE THREAD

**Issue by YushengLi** [Dynamoid/dynamoid#308]
I am trying to upgrade Dynamoid in our project from version 2.2.0 to 3.0.0, and keeps getting errors in `lib/dynamoid/undumping.rb` since some fields were not explicitly listed while declaring Models.

https://github.com/Dynamoid/dynamoid/blob/55d24359575247084dd90d2ff0602d130094d1fb/lib/dynamoid/undumping.rb#L24-L42

The issue here is back in version 2.2.0, when a field is not explicitly listed, field type would be `:string` by default, but since version 3.0.0, when a field is not explicitly listed, calling `options[:type]` in L25 will raised `NoMethodError (undefined method '[]' for nil:NilClass):`

I am not sure whether forcing explicitly listed all attributes is a good approach for DynamoDB since it does not require a strict schema, but maybe it should be documented in the README as a warning?

Thank you for putting together such a great Gem 🙇

**Comment by YushengLi** [comment]
Thanks for the response, I'm sincerly sorry for not being clear 🙇  let me describe the issue with more details

### Given the following DynamoDB table structure
```json
{
    "Table": {
        "AttributeDefinitions": [
            {
                "AttributeName": "pair",
                "AttributeType": "S"
            },
            {
                "AttributeName": "time",
                "AttributeType": "N"
            }
        ],
        "TableName": "FILTERED",
        "KeySchema": [
            {
                "AttributeName": "pair",
                "KeyType": "HASH"
            },
            {
                "AttributeName": "time",
                "KeyType": "RANGE"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": 1526466066.524,
        "ProvisionedThroughput": {
            "LastIncreaseDateTime": 1539939730.89,
            "LastDecreaseDateTime": 1539933548.64,
            "NumberOfDecreasesToday": 6,
            "ReadCapacityUnits": FILTERED,
            "WriteCapacityUnits": FILTERED
        },
        "TableSizeBytes": FILTERED,
        "ItemCount": FILTERED,
        "TableArn": "FILTERED",
        "TableId": "[FILTERED]",
        "StreamSpecification": {
            "StreamEnabled": true,
            "StreamViewType": "KEYS_ONLY"
        },
        "LatestStreamLabel": "2018-05-16T10:34:17.301",
        "LatestStreamArn": "[FILTERED]"
    }
}
```

I have a model definition

```ruby
class Bar::OneMinuteBar
  include Dynamoid::Document
  table name: "candlestick-01m", key: :pair

  field :closeBid, :number
  field :closeTime, :integer
  field :highBid, :number
  field :lowBid, :number
  field :openBid, :number
  field :openTime, :integer
  range :time, :integer
end
```

While executing the following query in Dynamoid v2.2.0
```ruby
Bar::OneMinuteBar.where(pair: 'BTC-JPY')
                 .scan_index_forward(false)
                 .record_limit(100)
                 .reverse_each
                 .to_a
```

It will return collection of Bar::OneMinuteBar
```ruby
[
  #<Bar::OneMinuteBar:0x00007fc7fce41e18 @attributes={:created_at=>nil, :updated_at=>nil, :closeBid=>0.716525e6, :closeTime=>1539940379863, :highBid=>0.716525e6, :lowBid=>0.716497e6, :openBid=>0.716497e6, :openTime=>1539940320363, :time=>1539940320000, :pair=>"BTC-JPY"}, @new_record=false, @associations={}, @attributes_changed_by_setter={}, @mutations_from_database=nil, @previously_changed={}, @mutations_before_last_save=nil>,
   #<Bar::OneMinuteBar:0x00007fc803930dc8 @attributes={:created_at=>nil, :updated_at=>nil, :closeBid=>0.716812e6, :closeTime=>1539940439833, :highBid=>0.716812e6, :lowBid=>0.716525e6, :openBid=>0.716525e6, :openTime=>1539940381503, :time=>1539940380000, :pair=>"BTC-JPY"}, @new_record=false, @associations={}, @attributes_changed_by_setter={}, @mutations_from_database=nil, @previously_changed={}, @mutations_before_last_save=nil>
   ...
]
```

But when I execute the same query in Dynamoid v3.0.0 it will raise errors in `dynamoid/lib/dynamoid/undumping.rb#L25`
```ruby
NoMethodError (undefined method '[]' for nil:NilClass):
```

While backtracing the code, I found out that same of the records contains additional fields such as :highAsk, :lowAsk, :closeAsk. in version v2.2.0, fields not explicitly declared will simply be ignored, but in version v3.0.0, it will railse an error while `undumping`, since there were no default type for field

So to make our table work with Dynamoid v3.0.0, I will have to explicitly declare all possibly existing columns.

```ruby
class Bar::OneMinuteBar
  include Dynamoid::Document
  table name: "candlestick-01m", key: :pair

  field :closeBid, :number
  field :closeTime, :integer
  field :highBid, :number
  field :lowBid, :number
  field :openBid, :number
  field :openTime, :integer
  field :highAsk, :number # Not declares in v2.2.0
  field :lowAsk, :number # Not declares in v2.2.0
  field :closeAsk, :number # Not declares in v2.2.0
  range :time, :integer
end
```

**Comment by andrykonchin** [comment]
Got it. Yeah, it definitely makes sense to ignore not declared fields during loading from dynamoDB. Will work on it soon.

**Comment by andrykonchin** [comment]
Fixed

@YushengLi please check the master branch

**Comment by andrykonchin** [comment]
We release new versions every 3-4 months so next one will be in a month or so.
